Project1:
  outputs:
    dev:
      account: "{{env_var('SF_ACC')}}"
      database: DBT_PROJECT
      password: "{{env_var('SF_PWD')}}"
      role: ACCOUNTADMIN
      schema: FOR_DBT
      threads: 1
      type: snowflake
      user: "{{env_var('SF_USER')}}"
      warehouse: COMPUTE_WH
  target: dev
